name: Update files

on:
  pull_request:
    branches: [main, dev]

permissions: 
  contents: write

jobs:
  update-lock:
    name: Update lockfile
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.40.2
          run-install: false
      - name: Pixi update
        run: |
          set -o pipefail
          pixi update --json | pixi exec pixi-diff-to-markdown >> diff.md
      - name: Commit lockfile
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com'
          git commit -aF diff.md
          git push
